[build]
  command = "apt-get install -y wkhtmltopdf && node ./import.js hu && bundle exec jekyll build && chmod 777 page2pdf && ./page2pdf"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.3.7"
  JEKYLL_ENV = "netlify"
