[build]
  command = "node ./import.js hu && cat _data/me.yml && bundle exec jekyll build && node page2pdf.js"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.3.7"
  JEKYLL_ENV = "netlify"
  NODE_VERSION = "20"
