#!/bin/bash
$(bundle show wkhtmltopdf-binary)/bin/wkhtmltopdf --page-size Letter \
  --margin-top 1in --margin-left 1in \
  --margin-right 1in --margin-bottom 1in \
  --print-media-type --dpi 300 \
  _site/assets/index.html _site/me.pdf
